In [1]:
import sqlite3 as sql
import pandas as pd

In [2]:
sql.connect('database1.sqlite')

In [3]:
#connection
conn = sql.connect('database.sqlite')
conn

In [4]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'col',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_hdf',
 'read_html',
 'read_iceberg',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'wide_to_long']

In [5]:
"select * from sqlite_master"

'select * from sqlite_master'

In [6]:
pd.read_sql_query("select * from sqlite_master", conn) #(query, db connection)

,type,name,tbl_name,rootpage,sql
0,table,Salaries,Salaries,2,CREATE TABLE Salaries (\n Id INTEGER PRIMAR...
1,index,salaries_year_idx,Salaries,16566,CREATE INDEX salaries_year_idx ON Salaries (Year)

In [7]:
pd.read_sql_query("select * from sqlite_master where type = 'table'",conn)

,type,name,tbl_name,rootpage,sql
0,table,Salaries,Salaries,2,CREATE TABLE Salaries (\n Id INTEGER PRIMAR...

### table info

In [8]:
pd.read_sql_query("PRAGMA table_info(Salaries)", conn)

    cid              name     type  notnull dflt_value  pk
0     0                Id  INTEGER        0       None   1
1     1      EmployeeName     TEXT        0       None   0
2     2          JobTitle     TEXT        0       None   0
3     3           BasePay  NUMERIC        0       None   0
4     4       OvertimePay  NUMERIC        0       None   0
5     5          OtherPay  NUMERIC        0       None   0
6     6          Benefits  NUMERIC        0       None   0
7     7          TotalPay  NUMERIC        0       None   0
8     8  TotalPayBenefits  NUMERIC        0       None   0
9     9              Year  INTEGER        0       None   0
10   10             Notes     TEXT        0       None   0
11   11            Agency     TEXT        0       None   0
12   12            Status     TEXT        0       None   0

In [9]:
pd.read_sql_query("PRAGMA table_info(salaries)", conn)

    cid              name     type  notnull dflt_value  pk
0     0                Id  INTEGER        0       None   1
1     1      EmployeeName     TEXT        0       None   0
2     2          JobTitle     TEXT        0       None   0
3     3           BasePay  NUMERIC        0       None   0
4     4       OvertimePay  NUMERIC        0       None   0
5     5          OtherPay  NUMERIC        0       None   0
6     6          Benefits  NUMERIC        0       None   0
7     7          TotalPay  NUMERIC        0       None   0
8     8  TotalPayBenefits  NUMERIC        0       None   0
9     9              Year  INTEGER        0       None   0
10   10             Notes     TEXT        0       None   0
11   11            Agency     TEXT        0       None   0
12   12            Status     TEXT        0       None   0

In [10]:
pd.read_sql_query("select * from Salaries", conn)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,567595.43,567595.43,2011,,San Francisco,
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,,538909.28,538909.28,2011,,San Francisco,
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

### Null values

In [11]:
pd.read_sql_query("select * from salaries where employeename is not null" ,conn)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,567595.43,567595.43,2011,,San Francisco,
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,,538909.28,538909.28,2011,,San Francisco,
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

In [12]:
pd.read_sql_query("select * from salaries where employeename is null" ,conn)

Empty DataFrame
Columns: [Id, EmployeeName, JobTitle, BasePay, OvertimePay, OtherPay, Benefits, TotalPay, TotalPayBenefits, Year, Notes, Agency, Status]
Index: []

In [13]:
pd.read_sql_query("select * from salaries where employeename not null" ,conn)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,567595.43,567595.43,2011,,San Francisco,
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,,538909.28,538909.28,2011,,San Francisco,
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

### distinct

In [14]:
pd.read_sql_query("select * from salaries",conn)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,567595.43,567595.43,2011,,San Francisco,
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,,538909.28,538909.28,2011,,San Francisco,
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

In [15]:
pd.read_sql_query("select jobtitle from salaries",conn)

                                              JobTitle
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
1                      CAPTAIN III (POLICE DEPARTMENT)
2                      CAPTAIN III (POLICE DEPARTMENT)
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
...                                                ...
148649                                       Custodian
148650                                    Not provided
148651                                    Not provided
148652                                    Not provided
148653                      Counselor, Log Cabin Ranch

[148654 rows x 1 columns]

In [16]:
pd.read_sql_query("select jobtitle,employeename,basepay from salaries ",conn)

,JobTitle,EmployeeName,BasePay
0,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,NATHANIEL FORD,167411.18
1,CAPTAIN III (POLICE DEPARTMENT),GARY JIMENEZ,155966.02
2,CAPTAIN III (POLICE DEPARTMENT),ALBERT PARDINI,212739.13
3,WIRE ROPE CABLE MAINTENANCE MECHANIC,CHRISTOPHER CHONG,77916
4,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",PATRICK GARDNER,134401.6
...,...,...,...
148649,Custodian,Roy I Tillery,0
148650,Not provided,Not provided,Not Provided
148651,Not provided,Not provided,Not Provided
148652,Not provided,Not provided,Not Provided
148653,"Counselor, Log Cabin Ranch",Joe Lopez,0

In [17]:
pd.read_sql_query("select DISTINCT jobtitle from SALARIES" , conn)

                                            JobTitle
0     GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
1                    CAPTAIN III (POLICE DEPARTMENT)
2               WIRE ROPE CABLE MAINTENANCE MECHANIC
3       DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
4                          ASSISTANT DEPUTY CHIEF II
...                                              ...
2154                    Sr Cnselor, Juv Hall (SFERS)
2155                  Forensic Toxicologist Supervis
2156                                      Conversion
2157                                       Cashier 3
2158                                    Not provided

[2159 rows x 1 columns]

In [18]:
pd.read_sql_query("select DISTINCT(jobtitle) from SALARIES" , conn)

                                            JobTitle
0     GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
1                    CAPTAIN III (POLICE DEPARTMENT)
2               WIRE ROPE CABLE MAINTENANCE MECHANIC
3       DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
4                          ASSISTANT DEPUTY CHIEF II
...                                              ...
2154                    Sr Cnselor, Juv Hall (SFERS)
2155                  Forensic Toxicologist Supervis
2156                                      Conversion
2157                                       Cashier 3
2158                                    Not provided

[2159 rows x 1 columns]

### Alias

In [19]:
pd.read_sql_query("select employeename from salaries",conn)

             EmployeeName
0          NATHANIEL FORD
1            GARY JIMENEZ
2          ALBERT PARDINI
3       CHRISTOPHER CHONG
4         PATRICK GARDNER
...                   ...
148649      Roy I Tillery
148650       Not provided
148651       Not provided
148652       Not provided
148653          Joe Lopez

[148654 rows x 1 columns]

In [20]:
pd.read_sql_query("select employeename Employee FROM SALARIES", conn)

                 Employee
0          NATHANIEL FORD
1            GARY JIMENEZ
2          ALBERT PARDINI
3       CHRISTOPHER CHONG
4         PATRICK GARDNER
...                   ...
148649      Roy I Tillery
148650       Not provided
148651       Not provided
148652       Not provided
148653          Joe Lopez

[148654 rows x 1 columns]

In [21]:
pd.read_sql_query("select employeename Name of Employees FROM SALARIES", conn)

DatabaseError: Execution failed on sql 'select employeename Name of Employees FROM SALARIES': near "of": syntax error

In [22]:
pd.read_sql_query("select employeename 'Name of Employees' FROM SALARIES", conn)

        Name of Employees
0          NATHANIEL FORD
1            GARY JIMENEZ
2          ALBERT PARDINI
3       CHRISTOPHER CHONG
4         PATRICK GARDNER
...                   ...
148649      Roy I Tillery
148650       Not provided
148651       Not provided
148652       Not provided
148653          Joe Lopez

[148654 rows x 1 columns]

In [23]:
pd.read_sql_query("select employeename Name_of_Employees FROM SALARIES", conn)

        Name_of_Employees
0          NATHANIEL FORD
1            GARY JIMENEZ
2          ALBERT PARDINI
3       CHRISTOPHER CHONG
4         PATRICK GARDNER
...                   ...
148649      Roy I Tillery
148650       Not provided
148651       Not provided
148652       Not provided
148653          Joe Lopez

[148654 rows x 1 columns]

In [24]:
pd.read_sql_query("select employeename as 'Name of Employees' FROM SALARIES", conn)

        Name of Employees
0          NATHANIEL FORD
1            GARY JIMENEZ
2          ALBERT PARDINI
3       CHRISTOPHER CHONG
4         PATRICK GARDNER
...                   ...
148649      Roy I Tillery
148650       Not provided
148651       Not provided
148652       Not provided
148653          Joe Lopez

[148654 rows x 1 columns]

In [26]:
pd.read_sql_query("select employeename as (Name of Employees) FROM SALARIES", conn)

DatabaseError: Execution failed on sql 'select employeename as (Name of Employees) FROM SALARIES': near "(": syntax error

In [25]:
pd.read_sql_query("select employeename as '(Name of Employees)' FROM SALARIES", conn)

       (Name of Employees)
0           NATHANIEL FORD
1             GARY JIMENEZ
2           ALBERT PARDINI
3        CHRISTOPHER CHONG
4          PATRICK GARDNER
...                    ...
148649       Roy I Tillery
148650        Not provided
148651        Not provided
148652        Not provided
148653           Joe Lopez

[148654 rows x 1 columns]

In [27]:
#function

def sql_query(q):
    return pd.read_sql_query(q,conn)

In [28]:
q = '''select * froM Salaries'''

sql_query(q)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,567595.43,567595.43,2011,,San Francisco,
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,,538909.28,538909.28,2011,,San Francisco,
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

### Ascending/Descending order by

In [29]:
q = '''select basepay,totalpay from salaries'''

sql_query(q)

             BasePay   TotalPay
0          167411.18  567595.43
1          155966.02  538909.28
2          212739.13  335279.91
3              77916  332343.61
4           134401.6  326373.19
...              ...        ...
148649             0       0.00
148650  Not Provided       0.00
148651  Not Provided       0.00
148652  Not Provided       0.00
148653             0    -618.13

[148654 rows x 2 columns]

In [30]:
q = '''select basepay,totalpay,otherpay from salaries order by 2'''

sql_query(q)

          BasePay   TotalPay   OtherPay
0               0    -618.13    -618.13
1               0       0.00          0
2               0       0.00          0
3               0       0.00          0
4               0       0.00          0
...           ...        ...        ...
148649  128808.87  362844.66   13126.31
148650  318835.49  390111.98   60563.54
148651  129150.01  471952.64  342802.63
148652  155966.02  538909.28  137811.38
148653  167411.18  567595.43  400184.25

[148654 rows x 3 columns]

In [31]:
q = '''select basepay,totalpay,otherpay from salaries order by 2 desc'''

sql_query(q)

             BasePay   TotalPay      OtherPay
0          167411.18  567595.43     400184.25
1          155966.02  538909.28     137811.38
2          129150.01  471952.64     342802.63
3          318835.49  390111.98      60563.54
4          128808.87  362844.66      13126.31
...              ...        ...           ...
148649             0       0.00             0
148650  Not Provided       0.00  Not Provided
148651  Not Provided       0.00  Not Provided
148652  Not Provided       0.00  Not Provided
148653             0    -618.13       -618.13

[148654 rows x 3 columns]

In [32]:
q = '''select basepay,totalpay,otherpay from salaries order by totalpay desc'''

sql_query(q)

             BasePay   TotalPay      OtherPay
0          167411.18  567595.43     400184.25
1          155966.02  538909.28     137811.38
2          129150.01  471952.64     342802.63
3          318835.49  390111.98      60563.54
4          128808.87  362844.66      13126.31
...              ...        ...           ...
148649             0       0.00             0
148650  Not Provided       0.00  Not Provided
148651  Not Provided       0.00  Not Provided
148652  Not Provided       0.00  Not Provided
148653             0    -618.13       -618.13

[148654 rows x 3 columns]

In [33]:
q = '''select basepay,totalpay,otherpay from salaries order by totalpay asc'''

sql_query(q)

          BasePay   TotalPay   OtherPay
0               0    -618.13    -618.13
1               0       0.00          0
2               0       0.00          0
3               0       0.00          0
4               0       0.00          0
...           ...        ...        ...
148649  128808.87  362844.66   13126.31
148650  318835.49  390111.98   60563.54
148651  129150.01  471952.64  342802.63
148652  155966.02  538909.28  137811.38
148653  167411.18  567595.43  400184.25

[148654 rows x 3 columns]

In [34]:
q = '''select employeename, jobtitle from Salaries where employeename = 'Not Provided'
'''

sql_query(q)

   EmployeeName                                 JobTitle
0  Not Provided  PUBLIC SAFETY COMMUNICATIONS DISPATCHER
1  Not Provided                   Public SafetyComm Disp

In [35]:
q = '''select employeename, jobtitle from Salaries where employeename = 'Not provided'
'''

sql_query(q)

   EmployeeName      JobTitle
0  Not provided  Not provided
1  Not provided  Not provided
2  Not provided  Not provided
3  Not provided  Not provided

In [36]:
q = '''select employeename, jobtitle from Salaries where employeename == 'Not Provided'
'''

sql_query(q)

   EmployeeName                                 JobTitle
0  Not Provided  PUBLIC SAFETY COMMUNICATIONS DISPATCHER
1  Not Provided                   Public SafetyComm Disp

### limit

In [37]:
q = '''select employeename, totalpay from Salaries order by 2 desc limit 10'''

sql_query(q)

           EmployeeName   TotalPay
0        NATHANIEL FORD  567595.43
1          GARY JIMENEZ  538909.28
2           David Shinn  471952.64
3            Amy P Hart  390111.98
4        Gary Altenberg  362844.66
5         John Goldberg  350403.41
6           Samson  Lai  347102.32
7       Ellen G Moffatt  344187.46
8  William J Coaker Jr.  339653.70
9        Gregory P Suhr  339282.07

In [38]:
q = '''select employeename, totalpay from Salaries order by 2 limit 10'''

sql_query(q)

         EmployeeName  TotalPay
0           Joe Lopez   -618.13
1      PAULETTE ADAMS      0.00
2       KAUKAB MOHSIN      0.00
3  JOSEPHINE MCCREARY      0.00
4       Roland Baylon      0.00
5    Felecia Phillips      0.00
6     Robert Giannini      0.00
7          Nelly Kuan      0.00
8     William Mathews      0.00
9       Gayle Mathews      0.00

In [39]:
q = '''select employeename, totalpay from Salaries order by 2
'''


sql_query(q)

              EmployeeName   TotalPay
0                Joe Lopez    -618.13
1           PAULETTE ADAMS       0.00
2            KAUKAB MOHSIN       0.00
3       JOSEPHINE MCCREARY       0.00
4            Roland Baylon       0.00
...                    ...        ...
148649      Gary Altenberg  362844.66
148650          Amy P Hart  390111.98
148651         David Shinn  471952.64
148652        GARY JIMENEZ  538909.28
148653      NATHANIEL FORD  567595.43

[148654 rows x 2 columns]

In [40]:
q = '''select employeename, totalpay from Salaries
    where employeename != 'Not provided'
    and 
    employeename != 'Not Provided'
    
'''


sql_query(q)

             EmployeeName   TotalPay
0          NATHANIEL FORD  567595.43
1            GARY JIMENEZ  538909.28
2          ALBERT PARDINI  335279.91
3       CHRISTOPHER CHONG  332343.61
4         PATRICK GARDNER  326373.19
...                   ...        ...
148643   Carolyn A Wilson       0.00
148644     Joann Anderson       0.00
148645        Leon Walker       0.00
148646      Roy I Tillery       0.00
148647          Joe Lopez    -618.13

[148648 rows x 2 columns]

In [41]:
q = '''select employeename, totalpay from Salaries
    where employeename != 'Not provided'
    or
    employeename != 'Not Provided'
'''


sql_query(q)

             EmployeeName   TotalPay
0          NATHANIEL FORD  567595.43
1            GARY JIMENEZ  538909.28
2          ALBERT PARDINI  335279.91
3       CHRISTOPHER CHONG  332343.61
4         PATRICK GARDNER  326373.19
...                   ...        ...
148649      Roy I Tillery       0.00
148650       Not provided       0.00
148651       Not provided       0.00
148652       Not provided       0.00
148653          Joe Lopez    -618.13

[148654 rows x 2 columns]

In [42]:
q = '''select employeename, totalpay from Salaries
    where employeename != 'Not provided'
    and
    employeename != 'Not Provided'
    order by 2
'''


sql_query(q)

              EmployeeName   TotalPay
0                Joe Lopez    -618.13
1           PAULETTE ADAMS       0.00
2            KAUKAB MOHSIN       0.00
3       JOSEPHINE MCCREARY       0.00
4            Roland Baylon       0.00
...                    ...        ...
148643      Gary Altenberg  362844.66
148644          Amy P Hart  390111.98
148645         David Shinn  471952.64
148646        GARY JIMENEZ  538909.28
148647      NATHANIEL FORD  567595.43

[148648 rows x 2 columns]

### operators

### Show jobtitle where overtimepay > 50k and excluded 'not provided' rows

In [43]:
q = 'select overtimepay from salaries'

sql_query(q)

         OvertimePay
0                  0
1          245131.88
2          106088.18
3           56120.71
4               9737
...              ...
148649             0
148650  Not Provided
148651  Not Provided
148652  Not Provided
148653             0

[148654 rows x 1 columns]

In [44]:
q = '''select jobtitle, overtimepay from Salaries
        where overtimepay > 50000
'''

sql_query(q)

                                  JobTitle   OvertimePay
0          CAPTAIN III (POLICE DEPARTMENT)     245131.88
1          CAPTAIN III (POLICE DEPARTMENT)     106088.18
2     WIRE ROPE CABLE MAINTENANCE MECHANIC      56120.71
3       BATTALION CHIEF, (FIRE DEPARTMENT)       89062.9
4       BATTALION CHIEF, (FIRE DEPARTMENT)      86362.68
...                                    ...           ...
2164               Parking Control Officer      54738.36
2165                          Not provided  Not Provided
2166                          Not provided  Not Provided
2167                          Not provided  Not Provided
2168                          Not provided  Not Provided

[2169 rows x 2 columns]

In [45]:
q = '''select jobtitle, overtimepay from Salaries
        where overtimepay > 50000
        and
        overtimepay != 'Not Provided'
'''

sql_query(q)

                                  JobTitle  OvertimePay
0          CAPTAIN III (POLICE DEPARTMENT)    245131.88
1          CAPTAIN III (POLICE DEPARTMENT)    106088.18
2     WIRE ROPE CABLE MAINTENANCE MECHANIC     56120.71
3       BATTALION CHIEF, (FIRE DEPARTMENT)     89062.90
4       BATTALION CHIEF, (FIRE DEPARTMENT)     86362.68
...                                    ...          ...
2160                      Transit Operator     51625.42
2161                      Transit Operator     52550.53
2162              Track Maintenance Worker     50265.23
2163             Diagnostic Imaging Tech I     74935.96
2164               Parking Control Officer     54738.36

[2165 rows x 2 columns]

### Show All Employess With A Total Pay Between 50,000 and 75,000

In [46]:
q = '''select employeename, totalpay from salaries
    where totalpay > 50000 and totalpay < 75000
    '''

sql_query(q)

             EmployeeName  TotalPay
0         MAMIKO NAKAMURA  74999.62
1           HEDLEY PRINCE  74998.73
2           LINDA BARNARD  74998.30
3        ANGELA WHITTAKER  74997.84
4                JANE CHU  74997.81
...                   ...       ...
33552     Stephanie Reidy  51785.23
33553  Maria Theresa Luna  52266.82
33554      Paul E Maltzer  51673.98
33555       Kevin I Dolar  50953.19
33556   Kathleen N Yumang  50348.91

[33557 rows x 2 columns]

In [47]:
# Show All Employess With A Total Pay Between 50,000 and 75,000

q = '''select employeename, totalpay from salaries
    where totalpay between 50000 and 75000'''

sql_query(q)

             EmployeeName  TotalPay
0         MAMIKO NAKAMURA  74999.62
1           HEDLEY PRINCE  74998.73
2           LINDA BARNARD  74998.30
3        ANGELA WHITTAKER  74997.84
4                JANE CHU  74997.81
...                   ...       ...
33552     Stephanie Reidy  51785.23
33553  Maria Theresa Luna  52266.82
33554      Paul E Maltzer  51673.98
33555       Kevin I Dolar  50953.19
33556   Kathleen N Yumang  50348.91

[33557 rows x 2 columns]

### Show All Employees With A BasePay less than 50,000 Or A TotalPay Greater Than 100,000

In [48]:
q = '''select employeename, basepay, totalpay from Salaries
    where basepay < 50000 
    or
    totalpay > 100000
    order by 3 desc
    limit 10'''

sql_query(q)

           EmployeeName    BasePay   TotalPay
0        NATHANIEL FORD  167411.18  567595.43
1          GARY JIMENEZ  155966.02  538909.28
2           David Shinn  129150.01  471952.64
3            Amy P Hart  318835.49  390111.98
4        Gary Altenberg  128808.87  362844.66
5         John Goldberg  104404.00  350403.41
6           Samson  Lai  186236.42  347102.32
7       Ellen G Moffatt  270222.04  344187.46
8  William J Coaker Jr.  257340.00  339653.70
9        Gregory P Suhr  319275.01  339282.07